server:
  port: 9003
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: neststore.vtt@gmail.com
    # https://myaccount.google.com/u/1/apppasswords
#    password: ymwuovhcpviucpjn
    password: yhtpnbgtljrfjcjb
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
