# API-GATEWAY
server:
  port: 9000

app:
  api-prefix: /api/v1

spring:
#  main:
#    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: http://localhost:9001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: book-service
          uri: http://localhost:9002
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:9003
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: cart-service
          uri: http://localhost:9004
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:9005
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
        - id: address-data-service
          uri: http://localhost:9006
          predicates:
            - Path=${app.api-prefix}/address/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: http://localhost:9007
          predicates:
            - Path=${app.api-prefix}/payments/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
