# ORDER-SERVICE
server:
  port: 9008

spring:
  application:
    name: order-orchestrator
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9094
    consumer:
      group-id: order-orchestrator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

